package logger

import (
	"fahLoadTest/utils/config"
	rotatelogs "github.com/lestrrat-go/file-rotatelogs"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
	"io"
	"path/filepath"
	"time"
)

// TODO настроить логгер
func LogInit(Config config.Cfg) (*zap.Logger, error) {

	encoderCfg := zapcore.EncoderConfig{
		TimeKey:        "TIME",
		LevelKey:       "L",
		NameKey:        "N",
		CallerKey:      "C",
		FunctionKey:    zapcore.OmitKey,
		MessageKey:     "M",
		StacktraceKey:  "S",
		LineEnding:     zapcore.DefaultLineEnding,
		EncodeLevel:    zapcore.CapitalLevelEncoder,
		EncodeTime:     zapcore.ISO8601TimeEncoder,
		EncodeDuration: zapcore.StringDurationEncoder,
		EncodeCaller:   zapcore.ShortCallerEncoder,
	}
	var level zapcore.Level
	switch Config.LOGLEVEL {
	case "DEBUG":
		level = zapcore.DebugLevel
	case "INFO":
		level = zapcore.InfoLevel
	case "WARN":
		level = zapcore.WarnLevel
	case "ERROR":
		level = zapcore.ErrorLevel
	case "PANIC":
		level = zapcore.PanicLevel
	case "FATAL":
		level = zapcore.FatalLevel
	default:
		level = zapcore.DebugLevel
	}
	filename, _ := filepath.Abs("fahTest/log/fahTest.log")
	writer := getWriter(filename)
	core := zapcore.NewCore(zapcore.NewConsoleEncoder(encoderCfg), zapcore.AddSync(writer), level)
	logger := zap.New(core)

	//logger, err := zap.NewDevelopment() //NewDevelopment()
	return logger, nil
}

func getWriter(filename string) io.Writer {
	// The actual file name generated by the Logger generating rotatelogs is demo.log.YYmmddHH
	// demo.log is a link to the latest log
	// Save the logs within 7 days, and split the logs every 1 hour (whole point)
	hook, err := rotatelogs.New(
		filename+".%Y%m%d%H", // No go style anti human format
		rotatelogs.WithLinkName(filename),
		rotatelogs.WithMaxAge(time.Hour*24*7),
		rotatelogs.WithRotationTime(time.Hour),
	)

	if err != nil {
		panic(err)
	}
	return hook
}
